# Generated by Django 5.1 on 2024-09-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_url_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
